# Generated by Django 5.2.4 on 2025-07-27 18:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extended_properties', models.JSONField(blank=True, default=dict)),
                ('slug', models.SlugField(help_text='Unique identifier for the template within organization', max_length=100)),
                ('name', models.CharField(help_text='Human-readable template name', max_length=200)),
                ('subject', models.CharField(help_text='Email subject line with template variables', max_length=255)),
                ('html_content', models.TextField(help_text='HTML email body with template variables')),
                ('text_content', models.TextField(blank=True, help_text='Plain text email body with template variables')),
                ('category', models.CharField(choices=[('auth', 'Authentication'), ('billing', 'Billing'), ('notifications', 'Notifications'), ('marketing', 'Marketing'), ('system', 'System')], default='notifications', help_text='Template category for organization', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active and can be used')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional template configuration and settings')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
                'unique_together': {('organization', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extended_properties', models.JSONField(blank=True, default=dict)),
                ('template_slug', models.CharField(help_text='Template slug at time of sending (preserved even if template deleted)', max_length=100)),
                ('recipient_email', models.EmailField(help_text='Email address of the recipient', max_length=254)),
                ('subject', models.CharField(help_text='Rendered email subject', max_length=255)),
                ('html_content', models.TextField(blank=True, help_text='Rendered HTML content')),
                ('text_content', models.TextField(blank=True, help_text='Rendered text content')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('complained', 'Complained')], default='pending', help_text='Current status of the email', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the email was successfully sent', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When the email was delivered', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if sending failed')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of retry attempts')),
                ('provider_message_id', models.CharField(blank=True, help_text='Message ID from email provider', max_length=255)),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Template context data used for rendering')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional email metadata and tracking information')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
                ('recipient_user', models.ForeignKey(blank=True, help_text='User account of recipient (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_emails', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, help_text='Template used for this email', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='email_service.emailtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_email', '-created_at'], name='email_servi_recipie_a87fff_idx'), models.Index(fields=['status', '-created_at'], name='email_servi_status_67a81c_idx'), models.Index(fields=['template_slug', '-created_at'], name='email_servi_templat_f6339d_idx')],
            },
        ),
    ]
