# Generated by Django 5.2.4 on 2025-10-15 12:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_organizationmembership_membership_user_org_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(blank=True, help_text='Email captured at time of action (preserved if user deleted)', max_length=254)),
                ('organization_slug', models.CharField(blank=True, help_text='Organization slug captured at time of action', max_length=100)),
                ('action', models.CharField(db_index=True, help_text="Action type (e.g., 'auth.login.success')", max_length=50)),
                ('resource_type', models.CharField(blank=True, help_text="Type of resource affected (e.g., 'user', 'organization')", max_length=50)),
                ('resource_id', models.UUIDField(blank=True, help_text='ID of the affected resource', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the client')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent string')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional structured data about the action')),
                ('success', models.BooleanField(default=True, help_text='Whether the action succeeded')),
                ('error_message', models.TextField(blank=True, help_text='Error message if action failed')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization context for the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='audit_user_time_idx'), models.Index(fields=['organization', 'timestamp'], name='audit_org_time_idx'), models.Index(fields=['action', 'timestamp'], name='audit_action_time_idx'), models.Index(fields=['ip_address', 'timestamp'], name='audit_ip_time_idx'), models.Index(fields=['success', 'timestamp'], name='audit_success_time_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_resource_idx')],
            },
        ),
    ]
