# Generated by Django 5.2.4 on 2025-08-07 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='If null, this is a global plan available to all organizations', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization'),
        ),
    ]
