# Generated by Django 5.2.7 on 2025-10-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="external_invoice_id",
            field=models.CharField(
                blank=True,
                help_text="External invoice ID from payment provider",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="external_payment_intent_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="External payment intent ID",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="provider",
            field=models.CharField(
                default="stripe",
                help_text="Payment provider (stripe, paypal, etc.)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="external_price_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="External price/plan ID from payment provider",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="external_product_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="External product ID from payment provider",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="provider",
            field=models.CharField(
                default="stripe",
                help_text="Payment provider (stripe, paypal, etc.)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="external_customer_id",
            field=models.CharField(
                blank=True,
                help_text="External customer ID from payment provider",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="external_subscription_id",
            field=models.CharField(
                blank=True,
                help_text="External subscription ID from payment provider",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="provider",
            field=models.CharField(
                default="stripe",
                help_text="Payment provider (stripe, paypal, etc.)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="stripe_invoice_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="plan",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="plan",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="plan",
            unique_together={("provider", "external_price_id")},
        ),
    ]
