# Generated by Django 5.2.4 on 2025-08-07 17:50

from django.db import migrations
from decimal import Decimal


def create_default_trial_plan(apps, schema_editor):
    """Create a default trial plan for new user registrations."""
    Plan = apps.get_model('billing', 'Plan')
    
    # Create trial plan if it doesn't exist
    trial_plan, created = Plan.objects.get_or_create(
        slug='free-trial',
        defaults={
            'name': 'Free Trial',
            'description': '14-day free trial with access to all features',
            'stripe_price_id': 'price_trial_placeholder',
            'stripe_product_id': 'prod_trial_placeholder',
            'amount': Decimal('0.00'),
            'currency': 'usd',
            'interval': 'month',
            'interval_count': 1,
            'trial_period_days': 14,
            'is_active': True,
            'features': {
                'users': 1,
                'storage_gb': 5,
                'projects': 3,
                'api_calls_per_month': 1000,
                'support': 'email',
                'features': [
                    'Basic dashboard',
                    'Core functionality',
                    'Email support',
                    'Mobile access'
                ]
            }
        }
    )
    
    if created:
        print(f"Created trial plan: {trial_plan.name}")
    else:
        print(f"Trial plan already exists: {trial_plan.name}")


def reverse_create_default_trial_plan(apps, schema_editor):
    """Remove the default trial plan."""
    Plan = apps.get_model('billing', 'Plan')
    Plan.objects.filter(slug='free-trial').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_make_plan_organization_nullable'),
    ]

    operations = [
        migrations.RunPython(
            create_default_trial_plan,
            reverse_create_default_trial_plan
        ),
    ]
