# Generated by Django 5.2.4 on 2025-09-01 14:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_remove_restrictive_invite_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extended_properties', models.JSONField(blank=True, default=dict)),
                ('key', models.SlugField(help_text="Unique identifier for the feature flag (e.g., 'advanced_analytics')", max_length=100, unique=True)),
                ('name', models.CharField(help_text="Human-readable name for the feature (e.g., 'Advanced Analytics Dashboard')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this feature flag controls')),
                ('is_enabled_globally', models.BooleanField(default=False, help_text='If true, this feature is enabled for all users regardless of other settings')),
                ('rollout_percentage', models.PositiveIntegerField(default=0, help_text='Percentage of users (0-100) who should have this feature enabled')),
                ('is_permanent', models.BooleanField(default=False, help_text='If true, this feature flag should not be deleted (core system feature)')),
                ('requires_restart', models.BooleanField(default=False, help_text='If true, application restart is required when this flag changes')),
                ('environments', models.JSONField(blank=True, default=list, help_text="List of environments where this flag is active (e.g., ['development', 'production'])")),
                ('active_from', models.DateTimeField(blank=True, help_text='Feature becomes active from this date (optional)', null=True)),
                ('active_until', models.DateTimeField(blank=True, help_text='Feature is active until this date (optional)', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this record belongs to. Can be null for global records.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeatureAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extended_properties', models.JSONField(blank=True, default=dict)),
                ('role', models.CharField(blank=True, help_text="User role this rule applies to (e.g., 'ADMIN', 'MANAGER')", max_length=100, null=True)),
                ('enabled', models.BooleanField(default=True, help_text='Whether this access rule grants (True) or denies (False) access')),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='Additional conditions for access (e.g., minimum account age, action count)')),
                ('reason', models.CharField(blank=True, help_text='Reason for this access rule (for auditing)', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this record belongs to. Can be null for global records.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='Specific user this rule applies to', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='feature_flags.featureflag')),
            ],
            options={
                'verbose_name': 'Feature Access Rule',
                'verbose_name_plural': 'Feature Access Rules',
                'indexes': [models.Index(fields=['feature', 'user'], name='feature_fla_feature_94ae07_idx'), models.Index(fields=['feature', 'role'], name='feature_fla_feature_23d4b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserOnboardingProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extended_properties', models.JSONField(blank=True, default=dict)),
                ('current_stage', models.CharField(choices=[('SIGNUP_COMPLETE', 'SIGNUP_COMPLETE'), ('EMAIL_VERIFIED', 'EMAIL_VERIFIED'), ('PROFILE_SETUP', 'PROFILE_SETUP'), ('ORGANIZATION_CREATED', 'ORGANIZATION_CREATED'), ('FIRST_TEAM_MEMBER', 'FIRST_TEAM_MEMBER'), ('FIRST_PROJECT', 'FIRST_PROJECT'), ('ADVANCED_FEATURES', 'ADVANCED_FEATURES'), ('ONBOARDING_COMPLETE', 'ONBOARDING_COMPLETE')], default='SIGNUP_COMPLETE', help_text='Current onboarding stage the user is in', max_length=100)),
                ('completed_stages', models.JSONField(default=list, help_text='List of completed onboarding stages')),
                ('total_actions_completed', models.PositiveIntegerField(default=0, help_text='Total number of onboarding actions completed')),
                ('progress_percentage', models.PositiveIntegerField(default=0, help_text='Percentage of onboarding completion (0-100)')),
                ('stage_started_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the current stage was started')),
                ('last_activity_at', models.DateTimeField(auto_now=True, help_text='Last time user progressed in onboarding')),
                ('onboarding_completed_at', models.DateTimeField(blank=True, help_text='When onboarding was fully completed', null=True)),
                ('custom_data', models.JSONField(blank=True, default=dict, help_text='Custom data for organization-specific onboarding tracking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this record belongs to. Can be null for global records.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Onboarding Progress',
                'verbose_name_plural': 'User Onboarding Progress',
                'indexes': [models.Index(fields=['user'], name='feature_fla_user_id_7d337d_idx'), models.Index(fields=['current_stage'], name='feature_fla_current_e46961_idx')],
            },
        ),
    ]
