# Generated by Django 5.2.4 on 2025-10-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_relationships'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0004_organizationmembership_membership_user_org_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['email'], name='account_email_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['email_verification_token'], name='account_verify_token_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['status', 'is_active'], name='account_status_active_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_email_verified'], name='account_email_verified_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['date_joined'], name='account_date_joined_idx'),
        ),
        migrations.AddIndex(
            model_name='accountauthprovider',
            index=models.Index(fields=['user', 'provider'], name='authprov_user_prov_idx'),
        ),
        migrations.AddIndex(
            model_name='accountauthprovider',
            index=models.Index(fields=['provider', 'provider_user_id'], name='authprov_prov_uid_idx'),
        ),
        migrations.AddIndex(
            model_name='accountauthprovider',
            index=models.Index(fields=['email'], name='authprov_email_idx'),
        ),
    ]
