# Generated by Django 5.2.4 on 2025-10-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_account_email_idx_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0005_add_soft_delete_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='password_reset_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['password_reset_token'], name='account_pwd_reset_token_idx'),
        ),
    ]
