# Generated by Django 5.2.4 on 2025-08-30 11:40

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='invite',
            name='email',
            field=models.EmailField(help_text='Email address of the person being invited', max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='Name of the organization (3-100 characters)', max_length=100, validators=[django.core.validators.MinLengthValidator(3, message='Organization name must be at least 3 characters long.')]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(help_text='URL-friendly version of the organization name', unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='sub_domain',
            field=models.CharField(help_text='Unique subdomain for the organization (3-50 characters, alphanumeric and hyphens only)', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3, message='Subdomain must be at least 3 characters long.'), django.core.validators.RegexValidator(message='Subdomain can only contain alphanumeric characters and hyphens. Cannot start or end with hyphen.', regex='^[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?$')]),
        ),
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together={('organization', 'email', 'status')},
        ),
        migrations.AddConstraint(
            model_name='invite',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='organizations_invite_expires_after_created'),
        ),
    ]
