# Generated by Django 5.2.4 on 2025-10-16 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organizationmembership_membership_user_org_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when organization was soft-deleted', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who initiated deletion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='deletion_reason',
            field=models.TextField(blank=True, help_text='Reason for organization deletion', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='scheduled_permanent_deletion',
            field=models.DateTimeField(blank=True, help_text='Scheduled date for permanent data deletion (typically 30 days after soft delete)', null=True),
        ),
    ]
