# Generated by Django 5.2.7 on 2025-10-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0005_add_soft_delete_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="extended_properties",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Extended properties for special organization flags (e.g., is_global_scope, protected)",
            ),
        ),
    ]
